### ISSUE TITLE
Mod not detected by Steamodded

### ISSUE THREAD

**Issue by GabrielSerealia** [OceanRamen/Saturn#14]
I followed the instructions for a new installation for Saturn and I was able to get Lovely and Steamodded to work they dont seem to detect the saturn mod. I extracted the mod into the Mods directory but nothing shows up in the Mods tab in game after launching.
I tested with other mods and they appear to work just fine.

**Here's a file tree of the mods directory:**
PS C:\Users\Gabriel\AppData\Roaming\Balatro\Mods> tree
Folder PATH listing for volume System
Volume serial number is 26E9-2399
C:.
├───.vscode
├───core
│   ├───config
│   ├───logic
│   └───utils
├───lovely
├───Steamodded
│   ├───assets
│   │   ├───1x
│   │   └───2x
│   ├───example_mods
│   │   └───Mods
│   │       ├───DeckSkinTemplate
│   │       ├───EditionExamples
│   │       │   └───assets
│   │       │       ├───1x
│   │       │       ├───2x
│   │       │       └───shaders
│   │       ├───ExampleJokersMod
│   │       │   └───assets
│   │       │       ├───1x
│   │       │       └───2x
│   │       ├───KeyboardController
│   │       │   └───localization
│   │       ├───LobcorpSoundtrack
│   │       │   └───assets
│   │       │       └───sounds
│   │       ├───NegateTexturePack
│   │       │   └───assets
│   │       │       ├───1x
│   │       │       └───2x
│   │       ├───RoyalFlush
│   │       │   └───assets
│   │       │       ├───1x
│   │       │       └───2x
│   │       └───SealExample
│   │           └───assets
│   │               ├───1x
│   │               └───2x
│   ├───libs
│   │   ├───json
│   │   └───nativefs
│   ├───localization
│   ├───lovely
│   └───src
├───Testing
└───UI

**Comment by GabrielSerealia** [comment]
User error, I misread the instructions put in Mods instead of Steamodded

**Comment by mpio-76** [comment]
> User error, I misread the instructions put in Mods instead of Steamodded

I have the same issue, were did you put the folder exactly?
